name: Test PAM360
on: workflow_dispatch
permissions:
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      run: |
        URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=pam360"
        AUTH="Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
        TOKEN=$(curl -s -H "$AUTH" "$URL" | jq -r .value)
        echo "$TOKEN"
        echo "$TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq .
